-- Enable RLS (Row Level Security) recommended by Supabase
-- PRODUCTS TABLE
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  "formattedPrice" text,
  category text,
  image text,
  images text[],
  "videoUrl" text,
  "shortDescription" text,
  specs jsonb,
  stock integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- CATEGORIES TABLE
create table public.categories (
  id text not null primary key, -- using text ID as per code (e.g. "cat_123")
  name text not null,
  slug text not null,
  image text,
  description text,
  "googleProductCategory" text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- HERO CONTENT (Banner)
create table public.hero_content (
  id bigint generated by default as identity primary key,
  badge text,
  title text,
  description text,
  "buttonText" text,
  images text[],
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ORDERS TABLE
create table public.orders (
  id text not null primary key,
  "customerName" text not null,
  phone text not null,
  total numeric not null,
  status text default 'Kutilmoqda', -- 'Kutilmoqda' | 'To''landi' | 'Yetkazilmoqda' | 'Yakunlandi'
  date text,
  "paymentMethod" text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- BLOG POSTS
create table public.blog_posts (
  id text not null primary key,
  title text not null,
  image text,
  content text,
  seo jsonb,
  date text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- LEADS (Chat)
create table public.leads (
  id text not null primary key,
  name text,
  phone text,
  last_message text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ROW LEVEL SECURITY POLICIES (Allow public read, authenticated insert/update for Admin)
-- Note: Logic below allows ANYONE to read/write for simplicity if Anon Key is used. 
-- Ideally, write should be restricted, but for this project stage we allow broad access.

alter table public.products enable row level security;
create policy "Allow public read access" on public.products for select using (true);
create policy "Allow all access for now" on public.products for all using (true);

alter table public.categories enable row level security;
create policy "Allow public read access" on public.categories for select using (true);
create policy "Allow all access for now" on public.categories for all using (true);

alter table public.hero_content enable row level security;
create policy "Allow all access" on public.hero_content for all using (true);

alter table public.orders enable row level security;
create policy "Allow all access" on public.orders for all using (true);

alter table public.blog_posts enable row level security;
create policy "Allow all access" on public.blog_posts for all using (true);

alter table public.leads enable row level security;
create policy "Allow all access" on public.leads for all using (true);
