-- ============================================================
-- LUXECORE / Telegram checkout rollout - phase 1 (additive)
-- Purpose:
--   Prepare production for the new server-side checkout flow
--   without breaking the currently deployed storefront.
--
-- Safe to run more than once:
--   - only ADD COLUMN IF NOT EXISTS
--   - only CREATE TABLE IF NOT EXISTS
--   - no destructive table rebuilds
--   - does NOT remove existing public order insert policies yet
-- ============================================================

begin;
set local lock_timeout = '5s';
set local statement_timeout = '60s';

-- New order fields used by the unified storefront + Telegram bot flow.
alter table if exists public.orders
  add column if not exists user_id uuid references auth.users(id) on delete set null,
  add column if not exists shipping_address text,
  add column if not exists city text,
  add column if not exists telegram_user_id bigint;

-- Bot order history queries filter by telegram_user_id.
create index if not exists idx_orders_telegram_user_id
  on public.orders (telegram_user_id)
  where telegram_user_id is not null;

-- Bot-owned tables. These already exist in current production, but keeping
-- them here makes the rollout idempotent for environments that are behind.
create table if not exists public.bot_users (
  telegram_id bigint primary key,
  name text,
  username text,
  phone text,
  address text,
  lang text default 'uz',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.promo_codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  discount_percent integer not null check (discount_percent between 1 and 90),
  active boolean default true,
  expires_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Defense in depth for bot-related tables in the exposed public schema.
alter table if exists public.bot_users enable row level security;
alter table if exists public.promo_codes enable row level security;

-- Keep admin access explicit and idempotent. public.is_admin() already exists
-- in the current production project and is used elsewhere in this codebase.
drop policy if exists "Admins manage bot users" on public.bot_users;
create policy "Admins manage bot users"
  on public.bot_users for all
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Admins manage promo codes" on public.promo_codes;
create policy "Admins manage promo codes"
  on public.promo_codes for all
  using (public.is_admin())
  with check (public.is_admin());

commit;
