-- Migration to create user_devices table for Firebase push notifications marketing

create table if not exists public.user_devices (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  telegram_id bigint references public.bot_users(telegram_id) on delete cascade,
  lead_id text references public.leads(id) on delete cascade,
  fcm_token text not null unique,
  device_info text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.user_devices enable row level security;

-- Policies for public.user_devices
drop policy if exists "Har kim o'z qurilmasi tokenini qo'sha oladi" on public.user_devices;
drop policy if exists "Har kim o'z qurilmasi tokenini yangilay oladi" on public.user_devices;
drop policy if exists "Adminlar barcha tokenlarni boshqara oladilar" on public.user_devices;

create policy "Har kim o'z qurilmasi tokenini qo'sha oladi"
  on public.user_devices for insert
  with check (true);

create policy "Har kim o'z qurilmasi tokenini yangilay oladi"
  on public.user_devices for update
  using (true);

create policy "Adminlar barcha tokenlarni boshqara oladilar"
  on public.user_devices for all
  using (public.is_admin())
  with check (public.is_admin());
